In [1]:
#Create two vectors
a <- rep(2010:2017, each = 4) # this uses the rep() function to repeat values
b <- round(runif(32, 0, 40)) # runif can be used to generate random numbers - in this case between 0 and 40
#Create data frame
c <- data.frame(a,b)

In [2]:
#head returns the top six rows
head(c)

a    b 
1 2010 28
2 2010 25
3 2010 29
4 2010  1
5 2011 37
6 2011 12

In [3]:
#Create a list of numbers
a <- 1:25 #The colon signifies a range
a

#Create a matrix with 5 rows and 5 columns
b <- matrix(a,nrow=5, ncol=5)
b

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 2     7   12   17   22  
[3,] 3     8   13   18   23  
[4,] 4     9   14   19   24  
[5,] 5    10   15   20   25

In [4]:
#Multiply b by 10
b*10
#Multiply b * b
b*b

[,1] [,2] [,3] [,4] [,5]
[1,] 10    60  110  160  210 
[2,] 20    70  120  170  220 
[3,] 30    80  130  180  230 
[4,] 40    90  140  190  240 
[5,] 50   100  150  200  250

[,1] [,2] [,3] [,4] [,5]
[1,]  1    36  121  256  441 
[2,]  4    49  144  289  484 
[3,]  9    64  169  324  529 
[4,] 16    81  196  361  576 
[5,] 25   100  225  400  625

In [5]:
#Extract first row
b[1,]
#Extract fourth column
b[,4]
#Extract third and fourth columns
b[,3:4] # The colon is used to define a numeric vector between the two numbers
#Extract first and fourth rows
b[c(1,5),] # The c() is used to create a numeric vector with the numbers separated by a comma
#Extract the value in the third row and fourth column
b[3,4]

[1]  1  6 11 16 21

[1] 16 17 18 19 20

[,1] [,2]
[1,] 11   16  
[2,] 12   17  
[3,] 13   18  
[4,] 14   19  
[5,] 15   20

[,1] [,2] [,3] [,4] [,5]
[1,] 1     6   11   16   21  
[2,] 5    10   15   20   25

[1] 18

In [6]:
#Return all the values in the column called "a"
c$a
#A different way of returning the column called "a"
c[,"a"]

[1] 2010 2010 2010 2010 2011 2011 2011 2011 2012 2012 2012 2012 2013 2013 2013
[16] 2013 2014 2014 2014 2014 2015 2015 2015 2015 2016 2016 2016 2016 2017 2017
[31] 2017 2017

[1] 2010 2010 2010 2010 2011 2011 2011 2011 2012 2012 2012 2012 2013 2013 2013
[16] 2013 2014 2014 2014 2014 2015 2015 2015 2015 2016 2016 2016 2016 2017 2017
[31] 2017 2017

In [7]:
colnames(c)

[1] "a" "b"

In [8]:
colnames(c) <- c("Year","Count")

In [25]:
#Read CSV file - creates a data frame called earnings
earnings <- read.csv("./notebooks/data/ACS_14_5YR_S2001_with_ann.csv")

Warning message in file(file, "rt"):
"cannot open file './notebooks/data/ACS_14_5YR_S2001_with_ann.csv': No such file or directory"

ERROR: Error in file(file, "rt"): cannot open the connection


In [22]:
#Show column headings
colnames(earnings)

#UID - Tract ID
#pop - estimated total population over 16 with income
#pop_m - estimated total population over 16 with income (margin of error)
#earnings - estimated median earnings
#earnings - estimated median earnings (margin of error)

[1] "X..DOCTYPE.html."

In [23]:
str(earnings)

'data.frame':	428 obs. of  1 variable:
 $ X..DOCTYPE.html.: Factor w/ 321 levels "  ","    ","      ",..: 313 224 135 230 228 229 231 237 236 225 ...
